// Generated by CoffeeScript 1.6.2
var Enemy;

Enemy = (function() {
  function Enemy(enemyprototype, path) {
    this.prototype = enemyprototype;
    this.path = simplifyPath(path);
    this.position = this.path[0];
    this.target = 1;
  }

  Enemy.prototype.tick = function() {
    var displacement, length;

    document.viewcontroller.renderSprite(this.prototype.image, this.position.x, this.position.y, 1);
    if (this.target === this.path.length) {
      alert('game over!');
      throw 'game over!';
    }
    displacement = {
      x: 0,
      y: 0
    };
    displacement.x = this.path[this.target].x - this.position.x;
    displacement.y = this.path[this.target].y - this.position.y;
    length = vectorLength(displacement);
    if (length < 5) {
      console.log('Rat node detected!');
      return this.target++;
    } else {
      this.position.x += displacement.x / length;
      return this.position.y += displacement.y / length;
    }
  };

  return Enemy;

})();
