// Generated by CoffeeScript 1.6.2
var GImage;

GImage = (function() {
  function GImage(location, owner) {
    var me;

    if (location == null) {
      location = 'broken.png';
    }
    this.image = new Image();
    this.image.src = "" + location;
    me = this;
    this.image.onload = function() {
      return me.onload.call(me);
    };
    this.loaded = false;
    this.owner = owner;
  }

  GImage.prototype.onload = function() {
    this.loaded = true;
    console.log('loaded image', this.image);
    if ((this.owner != null) && (this.owner.imageLoaded != null)) {
      return this.owner.imageLoaded();
    }
  };

  return GImage;

})();
