// Generated by CoffeeScript 1.6.2
var GMap;

GMap = (function() {
  function GMap(location) {
    var me;

    this.loaded = false;
    this.map = [];
    me = this;
    document.viewcontroller.loadImages("game/maps/" + location + ".png");
    this.image = "game/maps/" + location + ".png";
    this.background = document.viewcontroller.images["game/maps/" + location + ".png"];
    if (location != null) {
      $.get("game/maps/" + location + ".json", function(r) {
        me.loaded = true;
        return me.json = r;
      });
    } else {
      throw 'Invalid map supplied at gmap';
    }
  }

  return GMap;

})();
