// Generated by CoffeeScript 1.6.2
var GInputEvent,
  __slice = [].slice;

GInputEvent = (function() {
  function GInputEvent() {
    var data, type;

    type = arguments[0], data = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    this.type = type;
    switch (this.type) {
      case 'K':
        this.key = data[0];
        this.shift = data[1];
        break;
      case 'M':
      case 'MD':
        this.x = data[0];
        this.y = data[1];
        break;
      case 'D':
        this.dir = data[0];
    }
  }

  GInputEvent.prototype.toText = function() {
    var char, shift, textstring;

    textstring = '';
    switch (this.type) {
      case 'K':
        char = String.fromCharCode(this.key);
        shift = '';
        if ((this.shift != null) && this.shift) {
          shift = ' + SHIFT ';
        }
        textstring = "Keyboard event: key number " + this.key + " " + shift + " (which is '" + char + "')";
        break;
      case 'M':
        textstring = "Mouse click at (" + this.x + ", " + this.y + ")";
        break;
      case 'D':
        textstring = "D-pad cilcked (" + this.dir + ")";
        break;
      default:
        textstring = "Input type " + this.type;
    }
    return textstring;
  };

  return GInputEvent;

})();
