// Generated by CoffeeScript 1.6.2
var MapController;

MapController = (function() {
  function MapController(mapname) {
    this.relinquishcontrol = false;
    this.map = new GMap(mapname);
    this.enemies = [];
    this.towers = [];
    this.count = 0;
    document.viewcontroller.map.push(this.map);
    this.rat = new EnemyPrototype('game/assets/enemies/rat.json');
    this.tower = new TowerPrototype('game/assets/towers/tower.json');
    document.viewcontroller.prototypes.push(this.rat, this.tower);
  }

  MapController.prototype.spawnEnemy = function(enemyprototype) {
    return this.enemies.push(new Enemy(this.rat, this.map.json.nodes));
  };

  MapController.prototype.tick = function() {
    var e, t, _i, _j, _len, _len1, _ref, _ref1;

    if (this.count % 100 === 0) {
      this.spawnEnemy(this.rat);
      this.towers.push(new Tower(this.tower, this.map.json.towers[0].location));
    }
    viewcontroller.renderSprite(this.map.image, 0, 0, 1);
    _ref = this.enemies;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      e = _ref[_i];
      e.tick.call(e);
    }
    _ref1 = this.towers;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      t = _ref1[_j];
      t.tick.call(t);
    }
    return this.count++;
  };

  return MapController;

})();
