// Generated by CoffeeScript 1.6.2
var MapController;

MapController = (function() {
  function MapController(mapname) {
    this.relinquishcontrol = false;
    this.map = new GMap(mapname);
    this.enemies = [];
    this.enemies.push(new Enemy);
    document.viewcontroller.map.push(this.map);
    this.rat = new EnemyPrototype('game/assets/enemies/rat.json');
  }

  MapController.prototype.spawnEnemy = function(enemyprototype) {
    return this.enemies.push(new Enemy(this.rat));
  };

  MapController.prototype.tick = function() {
    var e, _i, _len, _results;

    viewcontroller.renderSprite(this.map.image, 0, 0, 1);
    _results = [];
    for (_i = 0, _len = enemies.length; _i < _len; _i++) {
      e = enemies[_i];
      _results.push(e.tick());
    }
    return _results;
  };

  return MapController;

})();
