// Generated by CoffeeScript 1.6.2
var Prototype;

Prototype = (function() {
  function Prototype(location) {
    this.loaded = false;
    if (location != null) {
      $.get(location, function(r) {
        me.loaded = true;
        me.json = r;
        return me.didLoad();
      });
    } else {
      throw 'Invalid prototype supplied.';
    }
  }

  Prototype.prototype.didLoad = function() {
    return true;
  };

  return Prototype;

})();
