// Generated by CoffeeScript 1.6.2
var Tower;

Tower = (function() {
  function Tower(towerprototype, position) {
    this.prototype = towerprototype;
    this.position = {
      x: position[0],
      y: position[1]
    };
  }

  Tower.prototype.tick = function() {
    var r, _i, _len, _ref, _results;

    document.viewcontroller.renderSprite(this.prototype.image, this.position.x, this.position.y, 1);
    _ref = document.viewcontroller.stack[0].rats;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      r = _ref[_i];
      if (vectorLength(vectorSubtract(r.position, this.position) < this.prototype.json.range)) {
        _results.push(r.didTakeDamage.call(r, this.prototype.json.damage));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  return Tower;

})();
